"""initial schema

Revision ID: 54ef9c33f96e
Revises:
Create Date: 2026-04-09 19:10:33.367112
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "54ef9c33f96e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "molecules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("inchikey", sa.String(length=64), nullable=False),
        sa.Column("canonical_smiles", sa.Text(), nullable=False),
        sa.Column("molecular_formula", sa.String(length=128), nullable=False),
        sa.Column("descriptor_snapshot", sa.JSON(), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("publish_status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_smiles"),
    )
    op.create_index(op.f("ix_molecules_inchikey"), "molecules", ["inchikey"], unique=True)
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_profiles_telegram_id"), "user_profiles", ["telegram_id"], unique=True)
    op.create_table(
        "cards",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("molecule_id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("topic_tags", sa.JSON(), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("enabled_hints", sa.JSON(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("provenance", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["molecule_id"], ["molecules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("molecule_id", "mode", name="uq_card_per_mode"),
    )
    op.create_index(op.f("ix_cards_is_published"), "cards", ["is_published"], unique=False)
    op.create_index(op.f("ix_cards_molecule_id"), "cards", ["molecule_id"], unique=False)
    op.create_table(
        "depiction_variants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("molecule_id", sa.String(length=36), nullable=False),
        sa.Column("render_preset", sa.String(length=64), nullable=False),
        sa.Column("rotation_seed", sa.Integer(), nullable=False),
        sa.Column("flip_x", sa.Boolean(), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("image_hash", sa.String(length=64), nullable=True),
        sa.Column("telegram_file_id", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["molecule_id"], ["molecules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_depiction_variants_molecule_id"), "depiction_variants", ["molecule_id"], unique=False)
    op.create_table(
        "naming_variants",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("molecule_id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column("normalized_signature", sa.Text(), nullable=False),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("source_ref", sa.Text(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["molecule_id"], ["molecules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("molecule_id", "mode", "locale", "answer_text", name="uq_naming_variant_answer"),
    )
    op.create_index(op.f("ix_naming_variants_molecule_id"), "naming_variants", ["molecule_id"], unique=False)
    op.create_index(
        op.f("ix_naming_variants_normalized_signature"),
        "naming_variants",
        ["normalized_signature"],
        unique=False,
    )
    op.create_table(
        "review_tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("molecule_id", sa.String(length=36), nullable=True),
        sa.Column("task_type", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["molecule_id"], ["molecules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_review_tasks_molecule_id"), "review_tasks", ["molecule_id"], unique=False)
    op.create_index(op.f("ix_review_tasks_status"), "review_tasks", ["status"], unique=False)
    op.create_index(op.f("ix_review_tasks_task_type"), "review_tasks", ["task_type"], unique=False)
    op.create_table(
        "user_settings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("difficulty_min", sa.Integer(), nullable=False),
        sa.Column("difficulty_max", sa.Integer(), nullable=False),
        sa.Column("topic_tags", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "user_stats",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("total_attempts", sa.Integer(), nullable=False),
        sa.Column("correct_answers", sa.Integer(), nullable=False),
        sa.Column("wrong_answers", sa.Integer(), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("best_streak", sa.Integer(), nullable=False),
        sa.Column("last_answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("card_id", sa.String(length=36), nullable=False),
        sa.Column("depiction_variant_id", sa.String(length=36), nullable=True),
        sa.Column("answer_locale", sa.String(length=8), nullable=True),
        sa.Column("raw_answer", sa.Text(), nullable=False),
        sa.Column("normalized_answer", sa.Text(), nullable=False),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("error_category", sa.String(length=64), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["depiction_variant_id"], ["depiction_variants.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["user_profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_attempts_card_id"), "attempts", ["card_id"], unique=False)
    op.create_index(op.f("ix_attempts_user_id"), "attempts", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_attempts_user_id"), table_name="attempts")
    op.drop_index(op.f("ix_attempts_card_id"), table_name="attempts")
    op.drop_table("attempts")
    op.drop_table("user_stats")
    op.drop_table("user_settings")
    op.drop_index(op.f("ix_review_tasks_task_type"), table_name="review_tasks")
    op.drop_index(op.f("ix_review_tasks_status"), table_name="review_tasks")
    op.drop_index(op.f("ix_review_tasks_molecule_id"), table_name="review_tasks")
    op.drop_table("review_tasks")
    op.drop_index(op.f("ix_naming_variants_normalized_signature"), table_name="naming_variants")
    op.drop_index(op.f("ix_naming_variants_molecule_id"), table_name="naming_variants")
    op.drop_table("naming_variants")
    op.drop_index(op.f("ix_depiction_variants_molecule_id"), table_name="depiction_variants")
    op.drop_table("depiction_variants")
    op.drop_index(op.f("ix_cards_molecule_id"), table_name="cards")
    op.drop_index(op.f("ix_cards_is_published"), table_name="cards")
    op.drop_table("cards")
    op.drop_index(op.f("ix_user_profiles_telegram_id"), table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_index(op.f("ix_molecules_inchikey"), table_name="molecules")
    op.drop_table("molecules")
    # ### end Alembic commands ###
